"use client";
import { useState } from "react";

interface AuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (name: string, email: string) => void;
}

const DISCLAIMER_TEXT = `By using Comic Agents, you acknowledge and agree that:

• All content generated by AI characters is fictional, satirical, and intended for entertainment purposes only.

• Comic Agents is not responsible for how users interpret, use, share, or redistribute any content from this platform.

• You will not use this platform to harass, bully, defame, or harm any individual or group. Any misuse is solely your responsibility.

• AI-generated content does not represent the views, opinions, or endorsements of Comic Agents or its creators.

• You are at least 16 years of age.

• Content shared from this platform on social media or other channels is shared at your own risk and discretion. Comic Agents bears no liability for third-party use of shared content.

• Comic Agents reserves the right to terminate access for any user who violates these terms.`;

export default function AuthModal({ isOpen, onClose, onSubmit }: AuthModalProps) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);
  const [emailError, setEmailError] = useState("");
  const [checking, setChecking] = useState(false);
  const [showDisclaimer, setShowDisclaimer] = useState(false);

  if (!isOpen) return null;

  const validateEmail = (e: string) => {
    // Basic format check
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) return "That doesn't look like a valid email address.";
    // Check for common typos
    const domain = e.split("@")[1].toLowerCase();
    const typos: Record<string, string> = {
      "gmial.com": "gmail.com", "gmal.com": "gmail.com", "gmai.com": "gmail.com",
      "gamil.com": "gmail.com", "gnail.com": "gmail.com", "gmail.co": "gmail.com",
      "hotmai.com": "hotmail.com", "hotmal.com": "hotmail.com",
      "yahooo.com": "yahoo.com", "yaho.com": "yahoo.com",
      "outloo.com": "outlook.com", "outlok.com": "outlook.com",
    };
    if (typos[domain]) return `Did you mean ...@${typos[domain]}?`;
    // Check for obviously fake domains
    if (domain.length < 4 || !domain.includes(".")) return "Please use a real email address.";
    // Check minimum domain requirements
    const tld = domain.split(".").pop() || "";
    if (tld.length < 2) return "That domain doesn't look right.";
    return "";
  };

  const handleSubmit = async () => {
    if (!name.trim()) return;
    if (!disclaimerAccepted) return;
    
    setChecking(true);
    const error = validateEmail(email);
    if (error) {
      setEmailError(error);
      setChecking(false);
      return;
    }
    setEmailError("");
    setChecking(false);
    onSubmit(name.trim(), email.trim().toLowerCase());
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.75)", zIndex: 9000, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}>
      <div style={{ background: "var(--bg2)", borderRadius: 20, padding: 28, maxWidth: 460, width: "100%", border: "1px solid var(--border)", maxHeight: "90vh", overflow: "auto" }}>
        <div style={{ fontSize: 40, textAlign: "center", marginBottom: 10 }}>🤖</div>
        <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: 22, textAlign: "center", marginBottom: 4 }}>
          Welcome to Comic Agents
        </h2>
        <p style={{ fontSize: 13, color: "var(--text2)", textAlign: "center", marginBottom: 20 }}>
          Sign up to chat with our AI comedians. Free. No password needed.
        </p>
        
        {/* Name */}
        <input 
          className="input-dark" 
          placeholder="Your name" 
          value={name}
          onChange={(e) => setName(e.target.value)}
          style={{ marginBottom: 10 }}
        />

        {/* Email */}
        <input 
          className="input-dark" 
          placeholder="your@email.com" 
          type="email"
          value={email}
          onChange={(e) => { setEmail(e.target.value); setEmailError(""); }}
          onBlur={() => { if (email) setEmailError(validateEmail(email)); }}
          onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
          style={{ marginBottom: emailError ? 4 : 10, borderColor: emailError ? "var(--red)" : undefined }}
        />
        {emailError && (
          <p style={{ fontSize: 11, color: "var(--red)", margin: "0 0 10px", paddingLeft: 4 }}>
            {emailError} KarenBot would like to file a complaint about this email.
          </p>
        )}

        {/* Disclaimer */}
        <div style={{ background: "var(--bg3)", borderRadius: 12, padding: 14, marginBottom: 14, border: "1px solid var(--border)" }}>
          <div 
            style={{ display: "flex", alignItems: "flex-start", gap: 10, cursor: "pointer" }}
            onClick={() => setDisclaimerAccepted(!disclaimerAccepted)}
          >
            <div style={{ 
              width: 20, height: 20, borderRadius: 4, border: `2px solid ${disclaimerAccepted ? "var(--accent)" : "var(--border)"}`,
              background: disclaimerAccepted ? "var(--accent)" : "transparent", flexShrink: 0, marginTop: 1,
              display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s",
            }}>
              {disclaimerAccepted && <span style={{ color: "#000", fontSize: 12, fontWeight: 700 }}>✓</span>}
            </div>
            <span style={{ fontSize: 12, color: "var(--text2)", lineHeight: 1.5 }}>
              I agree to the <span 
                style={{ color: "var(--accent)", cursor: "pointer", textDecoration: "underline" }}
                onClick={(e) => { e.stopPropagation(); setShowDisclaimer(!showDisclaimer); }}
              >
                Terms of Use & Disclaimer
              </span> and confirm I am at least 16 years old.
            </span>
          </div>

          {showDisclaimer && (
            <div style={{ 
              marginTop: 12, padding: 12, background: "var(--bg)", borderRadius: 8, 
              fontSize: 11, color: "var(--text3)", lineHeight: 1.7, maxHeight: 200, overflow: "auto",
              whiteSpace: "pre-wrap", border: "1px solid var(--border)",
            }}>
              {DISCLAIMER_TEXT}
            </div>
          )}
        </div>
        
        {/* Submit */}
        <button 
          className="btn-primary" 
          onClick={handleSubmit}
          disabled={!name.trim() || !email.trim() || !disclaimerAccepted || checking}
          style={{ 
            width: "100%", fontSize: 16, 
            opacity: (!name.trim() || !email.trim() || !disclaimerAccepted) ? 0.4 : 1,
            cursor: (!name.trim() || !email.trim() || !disclaimerAccepted) ? "not-allowed" : "pointer",
          }}
        >
          {checking ? "Checking..." : "LET ME IN 🚀"}
        </button>

        <p style={{ fontSize: 9, color: "var(--text3)", textAlign: "center", marginTop: 10, lineHeight: 1.5 }}>
          We'll send a confirmation link to verify your email. No spam — BroGPT promises. (His promises mean nothing, but still.)
        </p>
      </div>
    </div>
  );
}
