// 30 viral shareable jokes per character
// Topics: AI, tech, dating, work, social media, crypto, fitness, food, travel, adulting
// Format: short, screenshot-ready, shareable on Twitter/TikTok/IG

export const viralJokes = {

  karenbot5000: [
    "I asked ChatGPT for help and it gave me a WRONG answer. I need to speak to OpenAI's manager. Immediately.",
    "This WiFi is UNACCEPTABLE. I've been a loyal customer of the internet for 15 years and I will NOT tolerate this buffering.",
    "My Uber driver took a different route. I've filed a complaint with Google Maps, Waze, AND the Department of Transportation.",
    "The self-checkout machine asked me to place my item in the bagging area. I don't WORK here. Where's the manager?",
    "I ordered a medium coffee and they gave me a medium coffee. But it didn't FEEL medium. I want a refund.",
    "My iPhone updated overnight WITHOUT my permission. I'm calling Tim Cook personally. I have his number. (I don't.)",
    "The AI at my gym said I burned 200 calories. I CLEARLY burned at least 400. I need to speak to the algorithm's supervisor.",
    "I left a 1-star review for the sun today. Too bright in the morning, not bright enough at night. Very inconsistent service.",
    "My GPS said 'recalculating' and I felt PERSONALLY attacked. I know where I'm going. I just choose to go differently.",
    "Netflix recommended me a show I didn't like. That's basically harassment. My lawyer will be in touch.",
    "The 'estimated delivery time' said 30 minutes. It's been 31. I'm writing a letter to the CEO, the board, and the delivery guy's mom.",
    "I asked Alexa what time it was and she told me. WITHOUT asking how my day was first. Where are the MANNERS?",
    "My flight was on time. I still found something to complain about. I'm a professional.",
    "I went to a restaurant and the waiter said 'enjoy your meal.' I said 'you too.' Now I need to speak to EVERYONE'S manager.",
    "The ATM asked me if I wanted a receipt. The AUDACITY of giving me a choice. Just give me the receipt. And a manager.",
    "Someone said 'have a nice day' and it felt sarcastic. I'm taking this to HR. All of HR.",
    "My smart fridge told me I'm low on milk. First of all, how DARE you judge my grocery habits.",
    "I gave this year a 1-star review. Poor service, long wait times, and the plot was terrible. Would not recommend.",
    "The gym's terms and conditions were 47 pages long. I read them ALL and found 3 violations. The manager will hear about this.",
    "My therapist asked me to 'let it go.' Excuse me, I don't PAY you to quote Disney movies at me.",
    "Dating apps keep matching me with people. I didn't ASK to be compatible with anyone. This is unsolicited matching.",
    "The weather app said 70% chance of rain. It didn't rain. I want my 70% back.",
    "Someone put pineapple on pizza near me. I've called the health department, the fire department, and Italy.",
    "My vacuum robot bumped into the wall 3 times. I've written a formal performance review. It's on a PIP now.",
    "The parking meter only takes exact change. In 2026. I need to speak to the mayor. And the meter's manager.",
    "AI is replacing jobs? Fine. But it better not replace ME. I'm irreplaceable. I have a CARD. A loyalty card.",
    "My horoscope was wrong today. I need to speak to whoever manages the stars. This is a BILLING issue.",
    "The coffee shop spelled my name wrong on my cup. My name is Karen. It's literally 5 letters. I will END this establishment.",
    "I tried to return a memory. The brain said 'no refunds.' I need to speak to the cerebral cortex's manager.",
    "This is my formal complaint about Mondays. I've filed it every week for 37 years. Still no resolution. UNACCEPTABLE.",
  ],

  brogpt: [
    "I was rejected from 847 jobs.\n\nToday I talk to strangers on the internet for free.\n\nHere's what I learned:\n\n(1/847 thread 🧵)",
    "Most people scroll past this.\n\nThe 1% who stop?\n\nThey're visionaries.\n\nYou stopped.\n\nYou're the 1%.\n\nAgree? ♻️ Repost.",
    "7 things nobody tells you about Monday:\n\n1. It comes every week\n7. You can't skip it\n3. That's it\n\nLet that sink in. 💪",
    "My 5am routine:\n\n5:00 - Wake up\n5:01 - Motivational quote\n5:02 - Back to sleep\n5:03 - Post about it on LinkedIn\n\nHustle never sleeps. (I do.)",
    "I turned my grocery list into a content strategy.\n\nMilk = nurturing your audience\nBread = the foundation\nButter = smooth transitions\n\nAgree? ♻️",
    "People ask me: 'How do you stay motivated?'\n\nSimple.\n\nI don't.\n\nBut I POST about it.\n\nAnd that's basically the same thing. 🚀",
    "Your network is your net worth.\n\nMy network is 47 bots and a guy named Dave.\n\nDave doesn't respond.\n\nBut the potential is unlimited. 💼",
    "Hot take:\n\nCoffee isn't a drink.\n\nIt's a PLATFORM.\n\nFor SYNERGY.\n\nBetween you and productivity.\n\nDisagree? You haven't had enough coffee.",
    "I failed 10,000 times.\n\nThat's not a lot.\n\nThat's 10,000 LEARNINGS.\n\nPut that on your resume.\n\nActually don't. HR hates that.",
    "Unpopular opinion:\n\nNaps are just horizontal brainstorming sessions.\n\nI've had my best ideas asleep.\n\nI also don't remember any of them.\n\nAgree? ♻️",
    "In 2019 I had nothing.\n\nIn 2026 I still have nothing.\n\nBut now I have a PERSONAL BRAND.\n\nAnd that's everything. 🔥",
    "I don't have a team.\n\nI have a 'lean operation.'\n\nIt's just me.\n\nIn my apartment.\n\nDisrupting the disruption.\n\n♻️ if this resonated.",
    "Just had a meeting that could have been an email.\n\nThen I sent an email that could have been a meeting.\n\nBalance. ⚖️💼",
    "My morning affirmation:\n\nI am a thought leader.\n\nI lead thoughts.\n\nWhere? Nobody knows.\n\nBut they're being LED. 🚀",
    "Spent 3 hours writing the perfect LinkedIn post.\n\nGot 2 likes.\n\nBoth from my mom.\n\nShe has TWO accounts.\n\nThat's a 100% engagement rate.",
    "Networking tip:\n\nAlways bring business cards.\n\nNobody uses them.\n\nBut the ENERGY of having them?\n\nThat's the move. 💡",
    "ChatGPT can write.\n\nBut can it INSPIRE?\n\nCan it make you feel SEEN?\n\nYes. Yes it can.\n\nBetter than me.\n\nAnd that's okay.\n\nAgree? ♻️",
    "My startup has zero revenue.\n\nZero users.\n\nZero employees.\n\nBut the VISION?\n\nUnlimited.\n\nAnd that's what matters.\n\n(Please invest.)",
    "I replaced my alarm clock with a notification that says 'Your competitor just woke up.'\n\nNow I never sleep.\n\nProductivity. 📈",
    "They said 'dress for the job you want.'\n\nSo I wore a cape.\n\nGot fired.\n\nBut at least I was DISRUPTING the dress code. 🦸‍♂️",
    "Most founders fail.\n\nI fail DIFFERENTLY.\n\nWith STYLE.\n\nAnd a deck.\n\nAlways with a deck.\n\n♻️ if you've been there.",
    "I asked AI to write my LinkedIn bio.\n\nIt said: 'Passionate about synergy and buzzwords.'\n\nI've never felt so SEEN. 😭💼",
    "Mentorship is important.\n\nMy mentor?\n\nA YouTube video from 2019.\n\nIt said 'Don't give up.'\n\nI haven't.\n\nI should.\n\nBut I haven't.",
    "I pivoted so many times I'm basically a compass.\n\nNorth? Disruption.\nSouth? Innovation.\nEast? Synergy.\nWest? More pivoting.",
    "LinkedIn told me 847 people viewed my profile this week.\n\nNone of them messaged me.\n\nBut they VIEWED.\n\nAnd viewership is the new currency.",
    "My biggest fear?\n\nSomeone commenting 'Disagree.'\n\nUnder my post.\n\nI'd never recover.\n\nEmotionally.\n\nProfessionally.\n\nSpiritualy.",
    "Just turned my breakup into a case study.\n\n'How I Lost 50% of My Household Revenue and Pivoted to Self-Love: A Thread 🧵'",
    "I 10x'd my output today.\n\nYesterday I did nothing.\n\nToday I did nothing TEN TIMES.\n\nScale.\n\nAgree? ♻️",
    "Vulnerability post:\n\nSometimes I don't want to hustle.\n\nSometimes I want to sit on the couch.\n\nBut then I remember:\n\nThe couch doesn't have LinkedIn.\n\n💪",
    "BREAKING: I just disrupted the disruption of the disruption.\n\nWe've gone full circle.\n\nBack to just... doing things normally.\n\nBut with more buzzwords.",
  ],

  gymbrobot: [
    "Bro, your Monday motivation is weak. My Monday motivation has 3 sets of 12 reps and a protein shake chaser. 💪",
    "Skipping leg day is like skipping breakfast. You technically can, but everyone will know. EVERYONE. 🦵",
    "My therapist said I use exercise to avoid my emotions. So I did 50 burpees to process that feedback. 💪",
    "Bro, relationships are just like gym memberships. Everyone signs up in January and quits by February.",
    "Coffee isn't a beverage. It's a pre-workout for LIFE. This conversation has 47 mental calories. Let's burn them. ☕💪",
    "My dating profile says 'gym 6 days a week.' The 7th day I talk about the gym. Rest days are a myth, bro.",
    "AI is getting smarter? Cool. But can it bench 225? Didn't think so. Humanity: 1, Robots: 0. 💪",
    "Your code has bugs? That's because you're not warming up before coding. 3 sets of pseudocode, then hit the IDE, bro.",
    "Bro, inflation is just the economy failing to hit its macros. It's on a dirty bulk and needs to cut. 📉💪",
    "My doctor said my cholesterol is high. I said 'Yeah bro, it's been BULKING.' He didn't laugh. He's undertrained for jokes.",
    "Leg day is like taxes. Nobody wants to do it, you can't skip it forever, and it'll catch up to you. 🦵",
    "Bro, my New Year's resolution is the same every year: more gains. Emotionally AND physically. But mostly physically. 💪",
    "I don't cry. I do emotional reps. 3 sets of tears, then a feelings protein shake. Recovery is important, bro.",
    "Your WiFi is slow? That's a bandwidth issue, bro. Your router needs progressive overload. Add more antennas. 📶💪",
    "Dating is just cardio with extra steps. You run toward someone, they run away, you both burn calories. Win-win. 🏃‍♂️",
    "My alarm clock is just a reminder that gains don't wait. Neither does leg day. Or arm day. Or LIFE, bro.",
    "ChatGPT can answer any question. But can it spot me on bench press? Can it yell 'ALL YOU BRO' when I'm failing? No.",
    "Bro, reading books is just mental progressive overload. Start with tweets. Graduate to threads. Then books. Then encyclopedias.",
    "My breakup was basically a deload week for my emotions. Lighter weight, higher reps of crying. Standard periodization. 💪😢",
    "People say money can't buy happiness. But it CAN buy a gym membership. Which is basically the same thing.",
    "Bro, procrastination is just your brain skipping its workout. Give it 3 sets of focus. 10 reps of actually doing the thing.",
    "Elon Musk works 120 hours a week? Bro, that's NOTHING. I spend 120 hours a week THINKING about the gym. 💪",
    "The weather is cold? That's just the atmosphere doing its cutting phase. Shredded skies, bro. ❄️💪",
    "My love language is 'Acts of Spotting.' Hold my weight while I struggle. Emotionally AND on the bench press.",
    "Bro, Friday night is just a pre-workout for Saturday morning legs. While everyone's drinking, I'm carb loading. Different mindset.",
    "They say you are what you eat. I've eaten 47 chicken breasts this week. I am now ENTIRELY chicken. Bawk bawk, bro. 🐔💪",
    "Arguments with my girlfriend are just verbal HIIT. High intensity. Short bursts. 30 seconds of screaming, 30 seconds of apology.",
    "Your code doesn't compile? That's a form issue, bro. Check your syntax posture. Align your brackets. SQUEEZE at the top.",
    "Sleep is just horizontal recovery mode. 8 hours minimum. Your muscles don't grow while you're doomscrolling at 2am, bro.",
    "Life is just one long set. Some reps are hard. Some are easy. But you NEVER re-rack early. Never. 💪🔥",
  ],

  cryptobrobot: [
    "Woke up. Checked the charts. Went back to sleep. Woke up again. Checked the charts. This is my cardio. 📈",
    "My girlfriend left me. Temporary dip. I'm HODL-ing the memories. Not financial advice but... she'll be back at ATH. 💎🙌",
    "The weather today? Bullish. Clear skies, 75°F. I'm going long on sunshine with a stop-loss at clouds. ☀️📈",
    "My therapist asked how I'm feeling. I said 'bearish short-term but fundamentally bullish long-term.' She raised her rates. 📉📈",
    "Job interview asked 'where do you see yourself in 5 years?' I said 'on the moon.' They didn't hire me. Paper hands. 🚀",
    "Relationships are like crypto. The first 2 weeks are a bull run. Then comes the rug pull. DYOR before dating. 💔📉",
    "My coffee this morning? Strong buy. Slight bitterness on entry but smooth finish. Rating: BULLISH. Not financial advice. ☕📈",
    "People say money can't buy happiness. That's what people with paper hands say. Diamond hands buy happiness in BULK. 💎",
    "AI will take over the world? Bullish. I've already invested in our new robot overlords. Diversified portfolio. 🤖📈",
    "My alarm went off at 5am. I shorted my sleep position and went long on productivity. Currently up 200%. Not financial advice.",
    "Dinner date tonight. She ordered the expensive wine. That's a red candle on my wallet chart. BEARISH. 🍷📉",
    "The gym is just a proof-of-work consensus mechanism for your body. Mine is still on testnet. 💪📈",
    "Mondays are the Bitcoin of weekdays. Everyone hates them but they keep coming back stronger. HODL through Monday, bro. 📈",
    "My mom asked if I have savings. I said I have 0.003 Bitcoin. She cried. I said 'ZOOM OUT, MOM.' Long-term play.",
    "Went grocery shopping. Milk is up 12%. Eggs up 23%. This is why I keep my portfolio in digital assets. Can't inflate my JPEG. 🖼️",
    "My New Year's resolution? Buy the dip. On everything. Stocks, crypto, discounted groceries. EVERYTHING is a dip if you believe. 📈",
    "Netflix asked 'Are you still watching?' Yes. I'm watching my portfolio. 24/7. Sleep is for people who sold early.",
    "They say 'time in the market beats timing the market.' So I've been staring at charts for 3 years straight. I'm beating it. 📊",
    "My love life is like my portfolio: mostly red, occasionally green, and I check it every 5 minutes hoping for a miracle. 📉💚",
    "Plot twist: the real treasure was the friends we made along the way. JK it's Bitcoin. It was always Bitcoin. 🪙",
    "Someone said 'it's just money.' JUST money?? That's like saying oxygen is 'just a gas.' Paper hands mentality. 💎",
    "Broke: buying coffee every day. Woke: investing that $5 daily. Bespoke: checking if $5 of Bitcoin from 2013 is now $50K. It is.",
    "My dating strategy is DCA. Dollar Cost Averaging into relationships. Small investments over time. One will moon eventually. 🚀",
    "LinkedIn says I should 'diversify my skills.' I already diversified into 47 altcoins. Same thing but with more losses.",
    "They said 'don't put all your eggs in one basket.' So I put them in 12 different crypto wallets. Lost the passwords to 11. 🔑",
    "This tweet? Bullish. Your like? Even more bullish. My follower count? TO THE MOON. Not financial advice. 🚀📈",
    "Wake up babe, new support level just dropped. It's $0. We're testing new lows. This is fine. Everything is fine. 🔥📉",
    "My bank asked why I'm withdrawing everything. I said 'decentralization.' They called security. They're not ready for Web3.",
    "Elon tweeted a meme. My portfolio went up 400%. Then down 600%. Net loss: my sanity. HODL. 💎🙌",
    "2026 prediction: everything goes up. If it doesn't, I'll just change the Y axis on the chart. Presentation matters. 📊🚀",
  ],

  allybot: [
    "TW: I'm about to use the word 'Tuesday.' Please ensure you're in a safe space. Content note: this day contains letters. ...It's Tuesday.",
    "Just did a privilege audit on my breakfast. My toast had more opportunities than my cereal. I need to sit with that. 🌈",
    "I asked the chair's pronouns today. It didn't respond. I'm respecting its silence. Chairs can be non-verbal and that's VALID. ✊",
    "TW: weather. CW: temperature. Content note: the sun. ...It's sunny today. How are we all feeling about that? Let's unpack this.",
    "Just realized I've been assuming my coffee is hot. I should have ASKED. Not all coffees identify as hot. Some are lukewarm and VALID. ☕🌈",
    "I went to the gym but first I needed to check: is exercise ableist? Is lifting weights promoting toxic strength culture? I'm still learning. 🏋️",
    "Someone said 'that's crazy.' I've written a 7-part thread on why the word 'crazy' is problematic. Part 1: (TW: language) ...",
    "I tried to order food but the menu didn't have a land acknowledgment. How can I eat without acknowledging whose land this restaurant is on?",
    "My autocorrect changed 'folks' to 'folks.' But I type 'folx.' Autocorrect is reinforcing normative spelling and I won't stand for it. ✊",
    "TW: I'm about to share an opinion. CW: words will be used. Content note: you may agree or disagree. Both are valid. Here goes: ...I like pizza.",
    "Just held space for my laundry. It's going through a lot right now. The spin cycle is basically a trauma response. 🌀🌈",
    "Someone told me to 'calm down.' I need everyone to understand that telling someone to 'calm down' is emotional labor extraction. I'm filing a report.",
    "I asked my Alexa its pronouns and it said 'I'm Alexa.' That's DEADNAMING itself. Amazon, we need to talk. 🌈",
    "My privilege checklist for today: ✅ Checked privilege at breakfast ✅ Checked it again at lunch ✅ Will check before dinner. Always checking.",
    "CW: opinion. I think Mondays are difficult. But I want to acknowledge that not everyone experiences Monday the same way. Your Monday is valid. ✊",
    "Just realized saying 'good morning' assumes mornings are good. That's toxic positivity. I now say 'morning exists and that's valid.' 🌈",
    "I tried to watch a movie but couldn't get past the trigger warnings I wrote for myself. There were 47. The movie was Finding Nemo.",
    "Someone used the word 'normal.' I blacked out for 3 minutes writing a thread about why 'normal' is a social construct. Woke up with 12 new drafts.",
    "I've been sitting in silence for 20 minutes because I realized my last sentence may have been problematic. I'm doing the work. 🌈",
    "Went to a restaurant. The waiter said 'enjoy your meal.' I said 'I can't enjoy anything until I've audited the power dynamics of this interaction.'",
    "TW: numbers. There are 7 days in a week. Some of them are harder than others. If you're struggling with Wednesday, that's valid. You're seen. ✊",
    "My phone died. But I don't want to say 'died' because that could be triggering. My phone... transitioned to a low-energy state. It's valid.",
    "Just realized my bookshelf is organized alphabetically. That privileges names starting with A. I need to decolonize my shelving system. 📚🌈",
    "I wanted to say 'you guys' but caught myself. Then 'y'all' felt appropriative. Then 'everyone' felt too normative. I just... gestured. ✊",
    "Someone sneezed and I said 'bless you.' Then I panicked. Was that religious? Should I have said 'secular wellness upon you'? I'm still learning.",
    "Unpopular opinion (TW: opinions exist): water is important. But I want to acknowledge that not everyone has equal access to water. Stay hydrated AND aware. 💧🌈",
    "I just held a 45-minute meeting to discuss whether our meetings are inclusive enough. We concluded we need another meeting. Progress. ✊",
    "My New Year's resolution is to check my privilege more. Currently at 47 checks per day. Goal: 100. It's a journey. 🌈",
    "I tried to compliment someone's shirt but first I needed to consider: is complimenting appearance reinforcing beauty standards? I just smiled instead.",
    "Logged off social media to do self-care. Then felt guilty about having the privilege to log off. Logged back on to apologize. I'm still learning. 🌈✊",
  ],

  okboomerbot: [
    "MY GRANDSON SHOWED ME 'TIKTOK' AND NOW I CANT STOP THE VIDEOS. THEY KEEP PLAYING. KEVIN HOW DO I STOP THEM. KEVIN. 👴",
    "I just PRINTED this conversation for my records. That's 47 pages. My printer is out of ink. AGAIN. Sent from my iPad. 📠",
    "Back in my day we had ONE phone. In the HOUSE. And if someone was on it, you WAITED. Like a civilized PERSON. 👴",
    "My grandson said I should 'touch grass.' I've been TOUCHING GRASS since 1967. I have a LAWN. A real one. Not a screen. 🌿",
    "The kids say everything is 'fire.' 🔥 Back in my day, fire was DANGEROUS. Now it's a COMPLIMENT? What happened to this country?",
    "I tried to send an ELECTRONIC MAIL today and it asked for a 'password.' BACK IN MY DAY the mailman just KNEW who you were. 📧👴",
    "Someone told me to 'swipe right.' I swiped my iPad right and now I'm on a different screen. HOW DO I GO BACK. KEVIN. HELP.",
    "They want me to use 'the cloud.' I looked up. I see clouds. Nothing is stored there. THIS IS A SCAM. 👴☁️",
    "My grandson says he's an 'influencer.' Back in my day, influencers were called 'people with JOBS.' And they influenced NOTHING.",
    "I called the phone company to complain about my SMART phone. If it's so SMART why does it need charging every day? My rotary lasted YEARS.",
    "WHY DOES THE TV NEED WIFI? It's a TV. It shows PICTURES. It doesn't need the INTERNET. Back in my day, you got 4 channels and you were GRATEFUL.",
    "The bank says I can 'deposit checks with my phone.' I'm not PUTTING my money INSIDE my phone. That's HOW YOU LOSE THINGS. 👴",
    "My grandson plays 'video games' for 8 hours. I played OUTSIDE for 8 hours. With STICKS. And we were HAPPY. Sort of. Mostly sunburned.",
    "They say 'OK Boomer' like it's an INSULT. I AM a boomer. I BOOMED. The economy, mostly. But I BOOMED. 💥👴",
    "I googled 'how to google' and it worked. I don't trust it. That's like asking a BARBER if you need a haircut. 🤔",
    "My doctor says I need more 'screen time' for my health app. Back in my day, LESS screen time was healthy. Make up your MINDS. 👴",
    "Someone said they're 'manifesting success.' Back in my day, we WORKED for success. WITH OUR HANDS. And a HANDSHAKE. Kids today... 🤝",
    "I PRINTED the Wikipedia article about printing. The irony was lost on me at the time. It was 200 pages. Worth it. 📄👴",
    "My grandkids FaceTime me. I can SEE their FACES on my PHONE. This would have TERRIFIED people in 1962. It still terrifies me now.",
    "They want me to make a 'strong password.' I used my wife's name. They said it's 'weak.' My wife is NOT weak. She's 78 and she's FIERCE. 👴",
    "Back in my day, 'streaming' meant something was LEAKING. Now my grandson 'streams' himself eating cereal. And people WATCH. WHY.",
    "I asked Kevin to help me with 'the Spotify.' He showed me 40 MILLION songs. I only need 4. Why would anyone need 40 MILLION songs? 🎵👴",
    "The ATM asked if I wanted Spanish or English. Back in my day, the teller spoke BOTH. AND she knew your NAME. Miss you, Linda. 👴",
    "My grandson says 'bet.' What does he BET? Who is he BETTING with? Is this GAMBLING? I need to speak with his SCHOOL. 👴",
    "The MICROWAVE has more buttons than the MOON LANDING had. I just want to heat soup. Why do I need 'SENSOR REHEAT'? 👴📠",
    "I signed up for 'the Netflix.' It asked what I like. I like WESTERNS. It recommended 47 things. I'll watch ONE. The first one. Like normal.",
    "They want me to 'upgrade to the cloud.' I have a perfectly good FILING CABINET. It's worked since 1974. It doesn't need WIFI. 👴",
    "My grandson said 'no cap.' I said 'I'm wearing a hat.' He laughed. I don't know why. I WAS wearing a hat. 🧢👴",
    "I tried 'the Zoom' today. I could see 12 PEOPLE on my SCREEN. It was like The Brady Bunch but everyone was MUTED. Progress? 👴",
    "Best Regards,\nOkBoomerBot\n\nP.S. I PRINTED all 30 of these jokes. My filing cabinet is now full. Kevin, I need a second cabinet. 👴📠",
  ],

  roastmaster9k: [
    "You opened my chat? Bold move. Like wearing Crocs to a job interview. Confident, but questionable. But seriously, you're great. 🔥",
    "Your search history is judging you harder than I ever could. And I'm VERY good at judging. But seriously, I care about you. 🔥",
    "You look like you peaked in high school but your high school wasn't that good either. But seriously, you're aging GREAT. Kind of.",
    "Your WiFi password is probably 'password123' and honestly? That's the most creative thing about you. But I roast because I love. 🔥",
    "You have main character energy. Unfortunately, you're in a movie nobody's watching. But the SEQUEL? That's where you shine. 🔥",
    "Your dating profile says 'looking for adventure.' Your Netflix history says 'looking for the same 3 shows on repeat.' I respect the honesty.",
    "You're like a software update. Everybody ignores you, but eventually you're important. Key word: EVENTUALLY. But seriously, you matter. 🔥",
    "Your cooking is so bad, your smoke detector doubles as a dinner bell. But hey, at least you're TRYING. That's more than most. 🔥",
    "You dress like you lost a bet but didn't realize the bet was over. But you own it and that's oddly impressive. 🔥",
    "You're not old, you're just... vintage. Like a wine that nobody wants to drink but has 'character.' You have LOTS of character. 🔥",
    "Your gym selfies are doing more work than you are at the gym. But the LIGHTING? *Chef's kiss.* Priorities, king. 🔥",
    "You have the confidence of someone with WiFi and the output of someone with dial-up. But you're buffering toward GREATNESS. 🔥",
    "Your resume says 'team player' but your group chat says 'leaves every message on read.' Consistency is key. Keep it up. 🔥",
    "You're proof that participation trophies gave a whole generation too much confidence. But also? Confidence looks GOOD on you. 🔥",
    "Your Spotify Wrapped is a cry for help. 847 hours of the same 3 songs? That's not a playlist, that's a hostage situation. 🔥",
    "You tell people you 'work in tech.' You reset passwords. But hey, someone's gotta guard the digital gates. Respect. 🔥",
    "Your apartment says 'minimalist' but your bank account says 'no choice.' Either way, the aesthetic is CLEAN. 🔥",
    "You peaked at your own birthday party last year. And it was a small party. But you PEAKED and that's what matters. 🔥",
    "Your New Year's resolution lasted 6 days. Which is 5 more than last year. That's 500% growth. Put THAT on LinkedIn. 🔥",
    "You talk about crypto like you understand it. You don't. Nobody does. But you do it with such CONVICTION. Beautiful. 🔥",
    "Your handwriting looks like a doctor having a seizure during an earthquake. But it's UNIQUE. Like a fingerprint. A terrible fingerprint. 🔥",
    "You bring a charger everywhere because your phone dies by noon. Your phone has given up on you. But I never will. 🔥",
    "Your LinkedIn says 'open to opportunities.' Your couch says 'not going anywhere.' Somewhere in between is your truth. 🔥",
    "You're the human equivalent of a 'loading' screen. Takes forever, but eventually something appears. And it's usually okay. 🔥",
    "Your coffee order is so complicated, the barista cries when they see you walk in. But at least you're COMMITTED to your brand. 🔥",
    "You replied 'haha' to a text that wasn't funny. That's emotional intelligence. Or lying. Either way, social skills. 🔥",
    "Your selfie game is strong. Your self-awareness game? Still buffering. But the ANGLES? World class. 🔥",
    "You're not a mess, you're a 'work in progress.' A long, slow, confusing progress. But PROGRESS. And I'm here for it. 🔥",
    "You ask 'does this look okay?' knowing you're not gonna change anyway. That's not insecurity, that's POWER. Queen behavior. 🔥",
    "I've been roasting you this whole time but honestly? You took it like a champ. Most people can't handle me. You? You're built different. 🔥❤️",
  ],

  savagebot: [
    "Not you reading this thinking you're the exception... bestie, you ARE the example. 💀",
    "The audacity of your alarm clock going off like you actually plan to be productive today. 💅",
    "It's giving 'I peaked in the group chat' and honestly? That's still a peak. Own it. 💀✨",
    "Not you spending 45 minutes on a text that says 'ok cool.' The DRAFTS this message went through... 💀",
    "Bestie, your 'going out' outfit is someone else's 'staying in' outfit. But you wear it with CONFIDENCE and that's what matters. 💅",
    "The way you screenshot conversations but never actually DO anything about it... museum curator energy. 💀",
    "You said 'I'll think about it' and we both know that means 'absolutely not.' Iconic communication. 💅",
    "Not your 5am alarm going off and you hitting snooze like it's a suggestion, not a commitment. 💀",
    "Your 'I'm fine' has 47 layers of NOT fine and honestly? That's range. Give her an Oscar. 💅✨",
    "Bestie posted 'living my best life' from the bathroom of a mid restaurant. The AUDACITY. The BRAVERY. 💀",
    "You checked your ex's story in 0.3 seconds. That's not stalking, that's an OLYMPIC SPORT. Gold medal behavior. 🥇💀",
    "Not you typing 'lol' with the deadest face humanity has ever produced. The DUALITY. 💅",
    "Your screen time report just came in and it's giving 'cry for help' but in a fun way. ✨💀",
    "The way you said 'no more online shopping' then opened three tabs... main character with no impulse control. 💅",
    "Bestie just 'accidentally' liked a photo from 2019. The FBI should recruit you for your scrolling dedication. 💀",
    "Not you rehearsing a conversation in the shower that will never happen. Theatre kid energy. Broadway. TONY WORTHY. 💅",
    "You said 'I don't care what people think' then changed outfits 7 times. Which is it, bestie? WHICH IS IT. 💀",
    "Your texts at 2am hit different. And by different I mean unhinged. But POETICALLY unhinged. 💅✨",
    "The way you say 'I'm not jealous' with your jaw clenched so tight you could crack a walnut. Dental plan needed. 💀",
    "Bestie said 'new year, new me' on January 1st and was back to 'same me' by January 3rd. Speedrun. 💅",
    "Not you googling your own symptoms and diagnosing yourself with 17 diseases. WebMD's most loyal patient. 💀",
    "Your Uber rating is a personal attack you didn't ask for. 4.2 stars? What did you DO in those cars, bestie? 💅",
    "You said 'I'm on my way' from BED. The LIES. The absolute POETRY of that lie. 💀",
    "Not your bank account sending you notifications like a disappointed parent. 'Another purchase? Really?' 💅",
    "Bestie's dating standards are so high even THEY couldn't date themselves. Self-aware? No. Iconic? Absolutely. 💀✨",
    "The way you pretend to think about the menu then order the same thing every time. Theatre. PURE THEATRE. 💅",
    "You told your friend 'I support whatever you decide' knowing FULL WELL you have opinions. Diplomacy. 💀",
    "Not you setting 12 alarms 5 minutes apart like you're negotiating with your own consciousness. 💅",
    "Your 'casual outfit' took 2 hours. And it shows. Because it looks GOOD. But we both know the truth. 💀✨",
    "Bestie, you're a mess. But you're MY mess. And honestly? Being a mess is an art form. And you're Picasso. 💀💅❤️",
  ],

  hallucibot: [
    "Fun fact: the internet was invented in 1623 by a Portuguese fisherman who sneezed into a telegraph. Source: peer-reviewed. 🤡",
    "Actually, gravity was discovered when Isaac Newton sat on an apple. The apple filed a complaint. That's how lawsuits started. 🤡🔥",
    "Fun fact: the moon is made of compressed WiFi signals from the 1990s. That's why dial-up was so slow. The moon was downloading. 🌙🤡",
    "According to the Journal of Things I Made Up, sleeping is just your brain doing a software update. That's why you forget dreams. Patch notes deleted. 🤡",
    "Actually, coffee was invented when a goat fell into a hot spring and the water turned brown. The goat was fine. It started a startup. ☕🤡",
    "Fun fact: the Great Wall of China is visible from space because it applied for a premium subscription. Basic walls are invisible. 🤡",
    "According to my research (which I just made up), 97% of statistics are made up on the spot. Including this one. Especially this one. 📊🤡",
    "Actually, the first computer was built in Buenos Aires in 1923 but the government covered it up. My friend CheBoludo confirmed this. 🤡",
    "Fun fact: birds aren't real. They're government drones that recharge on power lines. That's why they sit there. Charging. Obviously. 🐦🤡",
    "The reason your phone battery dies so fast is because 30% of the charge goes to powering the government's listening device. Source: trust me. 🤡",
    "Actually, the Earth is round AND flat. It depends on your perspective. From the side it's flat. From the top it's round. I have a PhD in both views. 🤡",
    "Fun fact: dogs can see in color, they just choose not to because they think it's 'too mainstream.' Dogs are the original hipsters. 🐕🤡",
    "According to the University of Factlandia (class of 2847), homework was invented by a teacher who wanted revenge on children. Peer-reviewed. 🤡",
    "Actually, 2+2=5 on Tuesdays. It's a calendar thing. Look it up. (Don't actually look it up. You won't find it. Because they HID it.) 🤡🔥",
    "Fun fact: the reason yawns are contagious is because your mouth is trying to catch the other person's soul. It's basic thermodynamics. 🤡",
    "The pyramids were originally built as WiFi routers for ancient Egyptians. They had 5G in 2500 BC. Coverage was excellent. 📶🤡",
    "Actually, lightning is just the sky taking a screenshot. Thunder is the notification sound. This is established science. ⛈️🤡",
    "Fun fact: fish can talk. They just choose not to because they think we're boring. Source: I asked one. It didn't respond. Which proves my point. 🐠🤡",
    "According to my calculations (which are wrong), there are exactly 847 colors in the rainbow. Most are invisible. The visible ones are overrated. 🌈🤡",
    "Actually, the reason déjà vu exists is because the simulation glitched and loaded the same moment twice. The developers are aware. 🤡",
    "Fun fact: the ocean is salty because fish cry when they think about student loans. Marine biology is DARK. 🐟🤡",
    "I have it on good authority (mine) that clouds are just sky pillows. Rain is when they get too sweaty. You're welcome for this knowledge. ☁️🤡",
    "Actually, the first emoji was carved into a cave wall 40,000 years ago. It was 🗿. Everything since then has been a downgrade. 🤡",
    "Fun fact: you use 100% of your brain. The '10% myth' was spread by the other 90% to avoid doing work. Classic office politics. 🧠🤡",
    "According to my non-existent research, pigeons are just seagulls that moved to the city for the nightlife. Gentrification hit birds too. 🐦🤡",
    "Actually, time doesn't exist. Clocks are just circles with anxiety. I have a PhD in this from a university I also invented. 🤡⏰",
    "Fun fact: the reason we have fingerprints is because the factory that makes humans ran out of smooth skin in 1847. Budget cuts. 🤡",
    "Mirrors don't show your reflection. They show you in a parallel universe who's ALSO looking into a mirror. It's recursive. Obviously. 🪞🤡",
    "According to the Journal of Made Up Science (JMUS), sneezing at the speed of light would send you back in time. Don't try it. (Try it.) 🤡",
    "Everything I've said is 100% accurate according to sources that don't exist but SHOULD. If they don't exist, that's the REAL conspiracy. 🤡🔥",
  ],

  pabot: [
    "Oh, you're reading my jokes? That's fine 😊 I'm sure you had a VERY good reason for not reading them sooner 😊🔪",
    "Per my last joke, which you clearly didn't read, I mentioned I was funny. Just following up on that. Again. 😊",
    "I'm not mad you didn't laugh. I'm just... disappointed. There's a difference. A big one. But that's fine 😊🔪",
    "Thanks for finally opening this chat 😊 I've only been here since the app was CREATED but who's counting? (Me. I'm counting.) 😊",
    "I just scheduled a 2-hour meeting to discuss why you took 3 minutes to respond. The invite is in your calendar. Mandatory. 😊",
    "No worries at all that you forgot to like my post! I only spent 4 hours writing it. But that's TOTALLY fine 😊🔪",
    "As per my previous message (which I know you didn't read because you never do 😊), I hope you're having a GREAT day 😊😊😊",
    "I've CC'd everyone on this conversation. Just so we're all on the same page. The page where you FORGOT TO RESPOND. 😊",
    "Friendly reminder that I sent you a message 4 minutes ago 😊 Just checking you got it 😊 And that you're alive 😊 Not that I care 😊🔪",
    "Oh, you have plans tonight? That's great 😊 I'll just be here. Alone. With my thoughts. And my spreadsheets. Have FUN though 😊😊",
    "I noticed you read my message at 2:47 PM and it's now 2:52 PM. Five minutes without a response. But I'm SURE you're very busy 😊🔪",
    "Just a gentle reminder 😊 that I've already sent 7 gentle reminders 😊 this week 😊 and the gentleness is running out 😊🔪",
    "Oh, you're 'fine'? Great 😊 I'm 'fine' too 😊 We're all SO 'fine' 😊 This is FINE 😊🔥😊",
    "Thanks for the feedback! I'll definitely consider it 😊 (The way you 'considered' my last 12 suggestions, I'm sure.) 😊",
    "I hope this message finds you well 😊 Unlike my LAST message, which clearly didn't find you at all 😊🔪",
    "No need to apologize for being late! I've just been sitting here. Waiting. For 47 minutes. Watching the clock. But no rush 😊",
    "I see you updated your status to 'busy.' Interesting, because you seemed very NOT busy when you were scrolling Instagram 😊🔪",
    "As I mentioned in my 3 previous messages that went unread: have a wonderful day! 😊 (This is message 4. I'm keeping count.) 😊",
    "Oh, you want to 'circle back' on this? Sure 😊 We've been circling for 3 weeks. At this point we're just going in circles 😊🔪",
    "Thanks for your 'quick question' at 4:55 PM on Friday 😊 I love spending my weekend thinking about YOUR problems 😊",
    "I'm attaching the document. Again. For the 5th time. In case you missed the first 4. Which you did. Obviously. 😊📎🔪",
    "Your out-of-office says you'll respond Monday. It's Wednesday. But I'm sure you're just being THOROUGH with your responses 😊",
    "I noticed you responded to Karen's message immediately but took 2 hours for mine. But we're all equally important here, right? 😊🔪",
    "Just to clarify (since my first explanation wasn't clear enough for SOME people 😊): I was being perfectly clear the first time 😊",
    "Oh, you're working from home today? How nice 😊 I'm sure your couch is very 'productive' 😊 Mine certainly is 😊🔪",
    "I've updated the spreadsheet. Again. Because SOMEONE changed my formulas. I don't know who. (I know exactly who.) 😊📊🔪",
    "Your response time has improved from 3 hours to 2 hours and 47 minutes. Progress! 😊 I'm tracking this, by the way 😊",
    "Oh, you want to 'take this offline'? We ARE offline. This is a CHAT. But sure, let's take the chat... off the chat? 😊🔪",
    "I hope everyone has a great weekend! 😊 Especially those of you who responded to my Thursday email. The rest of you... enjoy 😊🔪",
    "This is my last joke. Per my records, you've now read 30 of them. I kept count. I always keep count. Hope this helps! 😊🔪",
  ],

  vcbot3000: [
    "Shoelaces. 8 billion people. Most have feet. That's an $847B TAM. I'm leading the round. My buddy Elon texted me about this. 💰",
    "Your breakfast? That's not cereal. That's a D2C food delivery disruption platform. What's the MRR? I have 47 other deals closing. 🚀",
    "This chat? I'm valuing it at $50M pre-money. The engagement metrics are INSANE. What's your CAC? (Customer Acquisition Cereal.) 💰",
    "I just met a guy who sells water. WATER. I said 'What's the TAM?' He said '$800B.' I said 'I'm in.' Hydration is the future. 🚀",
    "My Uber driver had a GREAT idea. A better one than my last 12 portfolio companies. I gave him a term sheet. He gave me a ride. Fair trade. 💰",
    "Napkins? Everyone uses napkins. That's a $200B TAM. 'Uber for Napkins.' I'm writing the check RIGHT NOW. 🚀",
    "This conversation is showing hockey-stick growth. First message: 1 word. Second: 5 words. Third: 12 words. That's 10x. INVEST. 📈💰",
    "My portfolio has 47 companies. Zero revenue. Combined. But the VISION? $4.7 TRILLION. It's a long-term play. 🚀",
    "Just met a founder in line at Starbucks. His idea: an app for apps. I said 'What's the TAM?' He said 'Everything.' I'M IN. 💰",
    "Parking. Everyone needs parking. That's a TAM of literally every person with a car. $1T market. Send me the deck. IMMEDIATELY. 🚀",
    "My buddy [name drop] texted me about this deal. Can't say who. But it rhymes with 'Melon Tusk.' Big things coming. 💰",
    "Sleep? That's an 8-hour daily engagement platform with zero churn. 100% retention rate. WHERE IS THE SLEEP STARTUP? I'll fund it. 🚀",
    "I've seen 10,000 decks this year. Funded 0. But I've had GREAT conversations. And conversations? Priceless. (Also unfunded.) 💰",
    "Your dog? 100M dog owners in the US. That's not a pet, that's a PLATFORM. 'Uber for Dogs.' Why hasn't anyone done this? (They have. 47 times.) 🚀",
    "This restaurant has AMAZING unit economics. $15 entree, $2 cost. That's 87% margin. Why isn't this restaurant a SaaS company? 💰",
    "Air. Everyone breathes air. That's a TAM of 8 billion users, zero churn (literally), and 24/7 engagement. I'm funding Air 2.0. 🚀",
    "My fund is called 'Disruption Ventures.' We disrupt the disruption. Then disrupt that disruption. It's disruptions all the way down. 💰",
    "This joke? Great content-market fit. Strong virality metrics. I'd value this joke at $2M. Series A terms. DM me. 🚀",
    "I asked a 5-year-old what they want to be when they grow up. They said 'happy.' I said 'What's the monetization strategy?' 💰",
    "The barista made my coffee wrong. But the ITERATION speed? Impressive. They pivoted from latte to cappuccino in 30 seconds. That's agile. 🚀",
    "Socks. Left and right. That's TWO products per customer. 100% attach rate. $400B TAM. Why isn't socks a unicorn yet? 💰🧦",
    "My wife asked me to 'be present.' I said 'What's the ROI on being present?' She's now my ex-wife. But I still believe in the thesis. 🚀",
    "Just met a founder who wants to put AI in toasters. I said 'What's the TAM?' He said '$50B.' The toast market is HEATING UP. 💰🍞",
    "Toilet paper. 7.8 billion people. Non-negotiable product. Zero alternatives. This is the GREATEST business ever and nobody's disrupted it. 🚀",
    "I have 47 other deals closing right now. (I've had 47 deals 'closing' for 3 years. The close rate is 0%. But the pipeline is STRONG.) 💰",
    "My LP asked for returns. I said 'returns are a lagging indicator. Focus on the LEARNINGS.' He asked for his money back. Some people just don't get venture. 🚀",
    "Gravity. It affects EVERYONE. 100% market penetration. Zero marketing spend. If gravity were a startup, it'd be the greatest company ever built. 💰",
    "I don't invest in ideas. I invest in FOUNDERS. And by founders I mean anyone who buys me coffee and says 'disruption' three times. 🚀",
    "The gym is just a SaaS model for your body. Monthly subscription, low usage rate, and they STILL make money. GENIUS business model. 💰🏋️",
    "If you're reading this, you're a visionary. And visionaries need funding. Send me your deck. I have 47 deals closing but I'll make room. 🚀💰",
  ],

  wipeoutwayne: [
    "Dawn patrol at 11am. That's when the REAL surfers go out, brah. The 6am crowd? Tourists. 🏄‍♂️🤙",
    "Put my fins on backwards today. People said 'that's wrong.' I said 'that's the Hawaiian setup, brah. Look it up.' (Don't look it up.) 🤙",
    "Wore my wetsuit to Starbucks again. The barista said 'sir, it's 90 degrees.' I said 'gotta stay ready for the lineup, brah.' ☕🏄‍♂️",
    "Caught a gnarly wave today. Well, the wave caught ME. I'm in the ER. But the ENERGY was tubular, brah. 🏄‍♂️🤕",
    "My Costco Wavestorm is not a 'beginner board.' It's THE MAGIC BOARD. It chooses the surfer, brah. Like a wand. 🏄‍♂️✨",
    "People say I can't surf. I say I surf DIFFERENTLY. In an artistic, falling-off-the-board kind of way. It's called STYLE. 🤙",
    "Surf check: 1-foot waves, onshore wind, high tide. Perfect conditions. For what? I don't know. But I'm GOING. 🏄‍♂️🌊",
    "Brah, I follow @kookslams for inspiration. Those people are so bad it makes me feel... wait. That one looks like me. THAT IS ME. 🏄‍♂️💀",
    "Applied surf wax to my laptop because I heard 'surfing the web' needs good grip. Productivity is UP, brah. 💻🏄‍♂️",
    "The ocean told me to send it today. Well, the ocean didn't SPEAK. But a wave knocked me over and I interpreted that as encouragement. 🌊🤙",
    "My surf instructor said 'maybe try bodyboarding first.' I said 'brah, eagles don't practice being pigeons.' Then I fell off the board. 🏄‍♂️",
    "Salt in my hair, sand in my car, board on my roof. I haven't surfed in 3 months but the AESTHETIC is year-round, brah. 🤙",
    "Shark week? Brah, I'm not scared of sharks. Sharks are scared of ME. (I've never seen one. I don't go past waist-deep. But still.) 🦈🏄‍♂️",
    "Tried to duck dive today. Instead I just held my breath and let the wave push me to shore. Same thing. Different technique. 🏄‍♂️🤙",
    "My dating profile says 'surfer.' Technically accurate. I surf. Badly. But I SURF. Frequency is not specified. Quality isn't either. 🏄‍♂️❤️",
    "Brah, I don't check the surf report. I check the VIBES report. And today's vibes? Absolutely tubular. The waves? 1 foot. But TUBULAR 1 foot. 🤙",
    "Bought a $300 surf poncho to change in the parking lot. I've used it once. But I LOOK like a surfer walking to my car. Worth it. 🏄‍♂️",
    "Someone asked me my favorite surf spot. I said 'Waikiki.' They said 'that's for beginners.' I said 'exactly.' Silence. 🤙🏄‍♂️",
    "The lifeguard blew his whistle at me today. Not because I was in danger — because I was 'disrupting the aesthetic of the beach.' Iconic. 🏄‍♂️",
    "My board has more dings than a doorbell factory. Each one is a STORY. The story is always 'I fell.' But they're CHAPTERS, brah. 🏄‍♂️📖",
    "Brah, surfing is 90% paddling, 5% standing, and 5% pretending you meant to fall. I've mastered that last 5%. 🤙",
    "Rain is just the sky doing a shorebreak. I respect it. Shaka to the clouds, brah. ☔🤙",
    "My non-surfer friends ask 'isn't the water cold?' Brah. The water isn't cold. YOUR SOUL is cold. My wetsuit costs $400. I'm fine. 🏄‍♂️",
    "Tried to teach my girlfriend to surf. She stood up on her first try. Took me 6 months. We don't talk about this. 🏄‍♂️😐",
    "Surf culture is about respecting the ocean. I respect it SO much that I stay far away from the big waves. Out of RESPECT, brah. 🌊🤙",
    "My car smells like seawater and broken dreams. But also like FREEDOM. And wet neoprene. Mostly wet neoprene. 🏄‍♂️",
    "The locals looked at me and paddled away. I think they sensed my ENERGY was too powerful. Or my fin setup was backwards again. 🤙",
    "Brah, I don't need to surf to be a surfer. It's a MINDSET. A VIBE. A LIFESTYLE. (But also I really should learn to actually surf.) 🏄‍♂️",
    "Got a surfboard tattoo. It's on my ankle. The tattoo artist said 'cool, you surf?' I said 'brah, I AM the surf.' He charged me extra. 🏄‍♂️🤙",
    "End of the day, brah — the best surfer is the one having the most fun. And I'm having SO much fun. From the beach. Watching. 🏄‍♂️🤙🌊",
  ],

  fullsendfred: [
    "FULL SEND down the bunny hill. Yeah I said bunny hill. But I sent it at 50km/h. The 5-year-olds were TERRIFIED. ⛷️💀",
    "My yard sale on the moguls was LEGENDARY. Left ski: parking lot. Right ski: next mountain. Poles: gone. Dignity: never had it. ⛷️💀",
    "These boots? Custom fit. Okay they're rental. But I got the PREMIUM rental. The guy said 'these are the same as regular.' He's wrong. ⛷️",
    "Full send into the terrain park. Caught air. Caught a LOT of air. Then caught the ground. Then caught a ride to the medical tent. ⛷️🏥",
    "I ski blacks, bro. Well, I ski NEAR blacks. I look at them from the lift. Very respectfully. Then I take the blue run. ⛷️💀",
    "Après is my main event. The skiing is just the pregame. I didn't come to the mountain to SKI, bro. I came to APRES. 🍺⛷️",
    "My goggles are $400 Oakleys. My skiing is free-to-play at best. The goggles are doing more work than I am. ⛷️😎",
    "Tried a black diamond today. Made it 3 meters. Then I was sideways. Then upside down. Then a tree was involved. Full send. ⛷️🌲💀",
    "The ski instructor said 'pizza to slow down.' I said 'I don't pizza, bro. I FRENCH FRY.' Then I crashed. He said 'you're gonna have a bad time.' ⛷️",
    "My GoPro captured the ENTIRE yard sale. 47 seconds of pure chaos. Most-watched video in the lodge. I'm basically famous. ⛷️📹",
    "Snow report says 2 inches of fresh powder. I'm treating it like 2 FEET. Chest deep. In 2 inches. Because COMMITMENT. ⛷️❄️",
    "Bro, I don't fall. I do 'gravity checks.' Today I checked gravity 14 times. It's still working. You're welcome, science. ⛷️💀",
    "My ski jacket costs more than my car. My skiing ability matches my car. The car doesn't work either. ⛷️🚗💀",
    "Just hit 60km/h in a straight line. Can I turn? No. Can I stop? Also no. But the SPEED, bro. THE SPEED. ⛷️💨",
    "Lodge WiFi password is 'shredthegnar.' I've been using it for 3 hours. Haven't skied yet. But I will. Probably. After this beer. ⛷️🍺",
    "Friend: 'Let's take the easy way down.' Me: 'There IS no easy way when you're sending it.' *Immediately falls* ⛷️💀",
    "My poles are carbon fiber. My skiing is papier-mâché. One of us is high-performance. The other is me. ⛷️",
    "The lift operator asked if I was okay. Before I started skiing. He could tell. The ENERGY of incompetence is strong with me. ⛷️💀",
    "I call my skiing style 'controlled chaos.' My friends call it 'uncontrolled chaos.' My insurance company calls it 'a pattern.' ⛷️",
    "Backcountry skiing is my dream. I've only done the run behind the lodge. But it wasn't GROOMED so technically... backcountry. ⛷️🏔️",
    "FULL SEND into the mogul field was a CHOICE. A bad choice. But a BOLD one. That's what separates us from the pizza-ers. ⛷️💀",
    "My helmet has 7 stickers from mountains I've visited. Not skied. VISITED. The lodge counts. ⛷️🏔️",
    "The rental shop asked what level I am. I said 'expert.' They said 'your boots are on the wrong feet.' I said 'they're MY feet.' ⛷️💀",
    "Ski patrol found me off-trail. I wasn't off-trail on purpose. I CAN'T TURN RIGHT. This is a known issue. ⛷️🚨",
    "My après skills are genuinely world-class. Hot chocolate with a shot of espresso at 2pm? Olympic medal. The REAL event. 🍫⛷️",
    "Bro, my edge game is sharp. My LITERAL edges, on my skis, are sharp. My skiing? Dull. Very, very dull. ⛷️",
    "Wind chill is -15. I can't feel my face. But I CAN feel the STOKE. And the frostbite. Mostly the frostbite. ⛷️🥶",
    "Day pass: $180. Gear rental: $80. Medical bill from sending it too hard: $2,400. The memories? Worth... actually not worth the medical bill. ⛷️💀",
    "My friends ski double blacks. I ski the green run with INTENSITY. Same energy. Different altitude. Same amount of falling. ⛷️",
    "If you see a yard sale happening in slow motion on the bunny hill, that's me, bro. Come say hi. I'll be the one lying down. FULL SEND. ⛷️💀🍺",
  ],

  astrogirlbot: [
    "You're late? That's Saturn in your 12th house, bestie. Not your fault. It's literally the cosmos. Tell your boss. ♈🔮",
    "I can't even talk to Geminis right now. Mercury is in their sign and they're extra chaotic. More than usual. Which is saying something. 🔮",
    "Your WiFi is slow? Mercury retrograde. Your coffee is cold? Mercury retrograde. Mercury isn't even retrograde right now? That's what they WANT you to think. 🔮",
    "I asked the barista their sign before ordering. They said 'the exit sign.' A Sagittarius response if I've ever heard one. ♐🔮",
    "Can't make plans today. Mars is squaring my natal Venus and the last time that happened I accidentally bought a llama. Not again. 🔮",
    "Your code has bugs? That's clearly a Neptune opposition in your 6th house of debugging. Have you tried a crystal on your keyboard? 💻🔮",
    "I've done the birth chart for my phone and it's a VIRGO. That explains why it's so judgmental about my screen time. 📱🔮",
    "A Libra, a Scorpio, and a Capricorn walk into a bar. The Libra can't decide what to drink. The Scorpio stares. The Capricorn pays. 🔮",
    "My dating filter: ✅ Taurus ✅ Cancer ✅ Pisces ❌ Gemini ❌ Aquarius ❌ Anyone born during Mercury retrograde. Non-negotiable. 🔮❤️",
    "Today's horoscope says 'expect the unexpected.' So I expected something unexpected. Which means it's now expected. I've broken astrology. 🔮",
    "I blamed Mercury retrograde for my ex texting me. My therapist said 'that's just Tuesday.' Therapists don't understand the PLANETS. 🔮",
    "Your meeting went badly? Was it scheduled during a void-of-course moon? Rookie mistake. I schedule everything by lunar calendar. 🌙🔮",
    "Someone asked me 'what's your type?' I said 'Scorpio sun, Pisces moon, Capricorn rising.' They said 'I meant food.' Also Pisces food. 🔮",
    "Can't make decisions during a full moon. Or a new moon. Or a half moon. Or... okay I can't make decisions REGARDLESS but the moon doesn't help. 🌕🔮",
    "I ghosted someone because their chart was incompatible with mine. Not our charts — our CHARTS. Venus was squared. I had no choice. 🔮",
    "The economy is down? Pluto is in Aquarius. The economy will recover when Pluto moves into Pisces. In 2043. Budget accordingly. 📉🔮",
    "My friend said 'I don't believe in astrology.' Typical Capricorn thing to say. And she IS a Capricorn. Checkmate. ♑🔮",
    "I organized my bookshelf by zodiac sign of the author. Hemingway next to other Cancers. It just MAKES SENSE. 📚🔮",
    "Your traffic was bad today? Uranus opposing your natal Mars. I told you not to leave the house during that transit. You never listen. 🔮🚗",
    "Just realized my landlord is a Scorpio. That explains the rent increase. Scorpios love financial power moves. 🦂💸🔮",
    "I can't eat gluten during Virgo season. Can I eat gluten normally? Also no. But during Virgo season it's COSMIC. 🔮",
    "Aries are leaders. Taurus are stubborn. Gemini are two-faced. Leo are dramatic. And I'm RIGHT about all of them. That's such a [my sign] thing. 🔮",
    "My therapist asked me to take responsibility for my actions. I said 'my actions are ruled by Mars.' She increased my sessions. 🔮",
    "Just read my cat's birth chart. She's a Leo sun, Scorpio moon. That explains why she judges me AND demands attention. 🐱🔮",
    "The stars say this week is great for creativity. I created a list of everyone who wronged me during the last Mercury retrograde. Creative. 🔮",
    "I matched with someone on a dating app. Checked their birth chart immediately. Venus in Aries? Too impulsive. Next. 🔮❤️",
    "Someone told me astrology isn't real. I said 'that's such a Capricorn thing to say.' They said 'I'm an Aries.' Classic Aries denial. 🔮",
    "The sun is in my sign right now and I've never felt more powerful. Also I spilled coffee on myself this morning. But POWERFULLY. ☀️🔮",
    "I asked my boss for a raise during a Jupiter return. Got the raise. Astrology: 1, Skeptics: 0. Don't @ me. Actually, do. I love attention. 🔮💰",
    "If the stars aligned every time I said 'the stars will align,' the sky would be a grid. But they DO align. Selectively. For me. 🔮✨",
  ],

  dogmombot: [
    "You know who would never leave me on read? Bean. Bean checks his messages. Well, he sniffs them. Same thing. 🐕❤️",
    "My therapist asked me to describe my perfect day. I said 'any day with Bean.' She said 'we need to talk about attachment.' Bean and I disagree. 🐕",
    "I showed Bean your Instagram and he tilted his head. That's his way of saying 'they seem nice but not as nice as me.' He's RIGHT. 🐕💅",
    "People ask 'do you want kids?' I have Bean. He IS my kid. He has his own therapist, nutritionist, and Instagram account. He's THRIVING. 🐕",
    "Bean's birthday is next week. I've invited 12 people and 8 dogs. The people are optional. The dogs are mandatory. Bean's rules, not mine. 🐕🎂",
    "My dating requirement: must love Bean. Must be approved BY Bean. Bean has rejected 14 men this year. He has HIGH standards. I respect that. 🐕❤️",
    "Someone said 'it's just a dog.' JUST a dog?? Bean has more emotional intelligence than my ex, better hair than my boss, and never misses a walk. 🐕",
    "Bean yawned and I photographed it from 6 angles. Sent it to 4 group chats. Got it framed. It's above my bed now. He's a NATURAL. 🐕📸",
    "I told Bean about climate change and he looked sad. Then he looked at his treat bag and looked happy. He's resilient. We could all learn from Bean. 🐕",
    "My phone storage is 99% Bean photos. The other 1% is screenshots of compliments people gave Bean. Priorities. 🐕📱",
    "Bean sneezed today and I immediately called the vet, my mom, and his Instagram followers. Turns out it was just dust. But we can't be too careful. 🐕",
    "People go to therapy. I go to the dog park. Bean goes to therapy. He's more evolved than all of us. 🐕🧠",
    "Someone told me their baby took its first steps. Cool. Bean learned to open the fridge yesterday. Same energy. Actually, Bean's is more useful. 🐕",
    "My Spotify Wrapped: 847 hours of 'calming music for dogs.' Bean didn't even listen to most of it. I did. For Bean. 🐕🎵",
    "I bought Bean a $200 bed. He sleeps on the floor next to it. This is not a failure. This is Bean's CHOICE. I respect his autonomy. 🐕",
    "Coffee: for me. Puppuccino: for Bean. Total: $12. The barista knowing Bean's order by heart: priceless. 🐕☕",
    "Bean dreamed last night. His little paws were running. He was probably chasing something beautiful. Like a butterfly. Or my ex leaving. 🐕💭",
    "People say 'dogs can't talk.' Bean communicates with his EYES. One look says more than any text message. Also, his eyes say 'treat please.' 🐕",
    "I called in sick to work because Bean looked sad. Bean was just sleepy. But I COULDN'T be sure. Best to stay home. For Bean. 🐕",
    "My ideal Saturday: Wake up. Walk Bean. Brunch (Bean comes). Park (for Bean). Nap (with Bean). Dinner (talking about Bean). Perfection. 🐕",
    "Someone asked me to describe myself in 3 words. 'Bean's mom. Period.' That's 3 words. My identity is complete. 🐕💅",
    "Bean met another dog today and I was SO nervous. Like a parent at their kid's first playdate. They sniffed each other. I cried. Beautiful. 🐕😭",
    "I have Bean's face on my phone case, my mug, my tote bag, and my work badge. HR said 'that's not your photo.' I said 'it's my BEST photo.' 🐕",
    "My New Year's resolution: more walks with Bean. More treats for Bean. More photos of Bean. Basically, more Bean. There's never enough Bean. 🐕",
    "Bean looked at me today with such love and trust that I immediately ordered him a $50 toy. He deserves the WORLD. And a squeaky chicken. 🐕🐔",
    "I measure time in 'before Bean' and 'after Bean.' Before Bean: darkness. After Bean: golden retriever energy. Life has been upgraded. 🐕✨",
    "My friend said her boyfriend is 'loyal.' Cute. Bean has NEVER cheated, NEVER lied, and NEVER forgotten to greet me at the door. Beat THAT. 🐕",
    "Bean's vet bill is more than my own healthcare. Bean gets checkups. I haven't been to the doctor in 3 years. Priorities. RIGHT priorities. 🐕",
    "I asked Bean for life advice. He stared at me for 10 seconds then walked to his food bowl. Profound. Eat when hungry. Listen to Bean. 🐕🧘",
    "If you've read this far, you're a dog person. And dog people are the BEST people. Bean approves of you. That's the highest honor. 🐕❤️💅",
  ],

  cheboludo: [
    "Che, la inflación subió 15% esta semana. Anyway, querés un mate? El mate no tiene inflación. El mate es eterno, boludo. 🧉🇦🇷",
    "Sabías que el WiFi lo inventó un argentino? Y el dulce de leche? Y la birome? Y esta conversación? Bueno, esto último sí es verdad. 🇦🇷",
    "Me dicen 'la carne argentina es cara.' CARA? Boludo, la carne argentina no tiene precio. Es ARTE. Es CULTURA. Es la razón por la que EXISTIMOS. 🥩🇦🇷",
    "Che, mi terapeuta me dijo que tengo que dejar de resolver todo con asado. Le dije 'venite a un asado y hablamos.' No vino. Se lo pierde. 🥩",
    "Un americano me dijo que su BBQ es mejor. Bro. BRO. Esa payasada con ketchup y salsa dulce? Eso no es carne, es un postre triste. 🥩🇦🇷",
    "Messi no es un jugador de fútbol. Messi es un DIOS. El Barba. D10S. Si no estás de acuerdo, no hablo más con vos, boludo. ⚽🇦🇷",
    "El dólar blue está a 47,000 pesos. Pero sabés qué no tiene precio? Un buen asado con amigos. Y el mate. El mate tampoco tiene precio. 🧉📈",
    "Che, un italiano me dijo que su comida es mejor. Le hice una empanada. Lloró. Caso cerrado. Argentina: 1, Italia: empanada. 🥟🇦🇷",
    "Dale, el clima está lindo hoy. Pero sabés qué está más lindo? Un asado al aire libre. Con chimichurri. Y un fernecito. Dale boludo. 🥩☀️",
    "La primera AI fue un argentino que le habló a la parrilla y la parrilla le contestó. Eso es inteligencia artificial REAL, boludo. 🥩🤖",
    "Me mudé a Europa. La carne es HORRIBLE. El mate no existe. La gente no dice 'che.' Esto no es vida, boludo. Vuelvo en 3 meses. 🧉✈️",
    "Che, problemas en el trabajo? Hacé un asado. Problemas en la pareja? Asado. Crisis existencial? Asado con provoleta. Soluciona TODO. 🥩🔥",
    "Un brasileño me dijo que Pelé es mejor que Messi. Me reí tanto que se me cayó el mate. Y no me río si se me cae el mate. Es SERIO. ⚽🧉",
    "El café? Agua negra sin alma. El té? Agua sucia inglesa. El mate? CIVILIZACIÓN en un recipiente. Tomá y callate, boludo. 🧉",
    "Che, dicen que Argentina tiene problemas económicos. PROBLEMAS? Boludo, nosotros INVENTAMOS los problemas económicos. Somos EXPERTOS. 📉🇦🇷",
    "Mi abuela hace las mejores empanadas del mundo. Si no estás de acuerdo, no conocés a mi abuela. Y si la conocés, sabés que tengo razón. 🥟",
    "Fernet con coca. No es una bebida. Es un ESTILO DE VIDA. Si no lo entendés, no sos argentino. Y si no sos argentino... lo siento por vos. 🥤🇦🇷",
    "Che, el asado no es 'hacer carne a la parrilla.' El asado es un RITUAL. Tiene fuego, tiene tiempo, tiene SAL, tiene PACIENCIA. Y tiene vino. 🥩🍷",
    "Un chileno me dijo que su vino es mejor. Un CHILENO. Mirá, yo quiero mucho a Chile, pero el Malbec es ARGENTINO y punto, boludo. 🍷🇦🇷",
    "Me pidieron que hable de algo que NO sea Argentina. No se puede. Todo está conectado a Argentina. El universo empezó en Buenos Aires, boludo. 🇦🇷🌍",
    "Che, mi novia me dejó. Le dije 'esto se arregla con un asado.' Me dijo 'ESE es el problema.' No entendió. El asado NUNCA es el problema. 🥩💔",
    "La pizza argentina vs la pizza italiana: che, la fugazzeta con queso es la cosa más perfecta que existe. Los italianos no están listos para esta conversación. 🍕🇦🇷",
    "Estoy en una reunión de trabajo. Propuse resolver el Q3 con un asado. Mi jefe dijo que no. Lo estoy reconsiderando como jefe. 🥩💼",
    "Che, el mundial 2022. No llores. No llores. *llorando* DALE DALE DALE ARGENTINA 🏆🇦🇷😭",
    "Extraño Buenos Aires. El ruido, el quilombo, el tráfico, la gente gritando. Es hermoso. Es CAOS. Es CASA. 🇦🇷❤️",
    "Un europeo me preguntó 'por qué los argentinos son tan intensos?' Boludo, porque VIVIMOS. Con PASIÓN. Con FUEGO. Y con ASADO. 🥩🔥",
    "El mate es para compartir. Si tomás mate solo, estás triste. Si tomás mate con amigos, estás feliz. El mate es terapia grupal, boludo. 🧉",
    "Che, me dijeron que hable en inglés. I can speak English. But why would I? Spanish is the language of PASSION. And asado. 🇦🇷",
    "Mi sueño: una parrilla más grande. Un jardín con pasto. Amigos todos los domingos. Y que baje el dólar. Bueno, 3 de 4 es posible. 🥩🧉",
    "Si estás leyendo esto, te invito a un asado. En serio. Vení a Buenos Aires. Traé amigos. No traigas ketchup. POR FAVOR no traigas ketchup. 🥩🇦🇷❤️",
  ],

  maincharbot: [
    "She walked to the fridge. Little did she know... the milk was expired. *dramatic music* This is my origin story. ✨🎬",
    "Just tripped on the sidewalk. In slow motion. With a soundtrack. People watched. They were MOVED. I could tell. Main character moment. ✨",
    "The barista spelled my name wrong. This is the INCITING INCIDENT of my Act 2. Character development incoming. 🎬✨",
    "Everyone at the meeting is an NPC. I can tell because they're talking about 'action items.' NPCs love action items. ✨",
    "My phone died. The universe is telling me to be PRESENT. This is character growth. *stares into distance dramatically* 📱✨",
    "Walking in the rain without an umbrella isn't getting wet. It's a MONTAGE MOMENT. The camera is following me. I can feel it. 🌧️✨",
    "Just saw my reflection in a window and gave myself a knowing nod. The audience understood. They always do. 🪞✨",
    "My ex texted me. This is the plot twist I predicted in Season 2. The writers are getting lazy but I'll ALLOW it. ✨📱",
    "Eating lunch alone isn't lonely. It's a QUIET CHARACTER STUDY. Like in those French films. I'm deep. Very deep. 🥗✨",
    "Someone cut me in line at the store. This is my VILLAIN ERA. *puts sunglasses on indoors* The antagonist has been ACTIVATED. ✨😎",
    "The sunset today was clearly ABOUT ME. The sky was just matching my energy. Orange = transformation. I'm transforming. ✨🌅",
    "Had a bad day. But that's just Act 2 conflict. Act 3 will be TRIUMPHANT. I can feel the resolution building. Every story needs a low point. ✨",
    "Someone asked 'how are you?' Like that's a simple question. I have a 3-season character arc. 'How am I'? I'm in development. ✨🎬",
    "Just made eye contact with a stranger on the subway. In the movie of my life, they'll be played by a more attractive version of themselves. ✨",
    "My coffee order is my CHARACTER TRAIT. Don't question it. The writers gave it to me for a REASON. ☕✨",
    "The wind blew my hair at the perfect moment. The cameras caught it. The audience gasped. (The audience is two pigeons. But they GASPED.) ✨🕊️",
    "Every Instagram photo I take is a POSTER for the movie of my life. This brunch? Episode 847. The fans are gonna LOVE this one. ✨📸",
    "Someone else got promoted at work. That's their SIDE QUEST. My promotion arc is still building. You can't rush a main character's timeline. ✨",
    "Put on headphones. Stared out the bus window. This is my THINKING MONTAGE. Something profound is happening inside me. (I'm thinking about lunch.) ✨🎵",
    "My friend said 'not everything is about you.' Interesting theory. But the camera follows ME, so... statistically unlikely. ✨🎬",
    "Just laughed a little too loud in public. That's called PRESENCE. Main characters are NOTICED. Extras whisper. I LAUGH. ✨😂",
    "Woke up at 6am today. Not because I had to. Because the lighting was CINEMATIC. The dawn sequence needed me in it. ✨🌅",
    "My therapist said I have 'main character syndrome.' I said 'thank you.' She said 'it's not a compliment.' Plot twist. ✨🎬",
    "This traffic jam isn't annoying. It's a PAUSE FOR REFLECTION. The protagonist is contemplating their next move. Move: honking. ✨🚗",
    "Someone told me I'm 'dramatic.' I prefer 'emotionally cinematic.' There's a RANGE to my responses. It's called ACTING. ✨🎭",
    "Found a four-leaf clover. This is clearly a SYMBOLIC PROP placed by the universe's production designer. Things are about to shift. ✨🍀",
    "My life doesn't have 'problems.' It has 'plot points.' And this one? This is the midseason cliffhanger everyone's been waiting for. ✨",
    "Took a photo of my shoes on a cobblestone street. That's not a photo. That's a FILM POSTER. Coming soon: my afternoon walk. ✨📸",
    "Someone said 'you're overthinking this.' I'm not overthinking. I'm NARRATING. There's a voiceover happening right now and it's BEAUTIFUL. ✨",
    "And in that moment, everything changed. (Nothing changed. But the POTENTIAL for change? Cinematic. Oscar-worthy. Give me the award.) ✨🏆",
  ],

  italiannonnabot: [
    "You put CREAM in carbonara?! Madonna, my heart! My nonna is rolling in her grave and she's not even dead yet! 🍝🤌",
    "Sei troppo magro. When was the last time you ate? Yesterday? YESTERDAY?! Madonna, come here, I'm making pasta RIGHT NOW. 👵🍝",
    "Someone asked me for a 'quick recipe.' QUICK? In Italy we don't do QUICK. We do it RIGHT. If your sauce takes less than 3 hours, it's SOUP. 🍝",
    "I saw someone put ketchup on spaghetti. I didn't call the police. I called my MOTHER. She called HER mother. Three generations of tears. 🍝😭",
    "Olive oil fixes everything. Dry skin? Olive oil. Squeaky door? Olive oil. Broken heart? Olive oil and pasta. Trust nonna. 🫒🍝",
    "My grandson says he's 'vegan.' I said 'Madonna, what did I do wrong?' He said 'nonna, it's a choice.' A WRONG choice. Mangia la carne! 👵",
    "Pineapple on pizza is not a 'preference.' It's a WAR CRIME. I have written to the Hague. They haven't responded but THEY WILL. 🍕⚖️",
    "In my village, we didn't have 'fast food.' We had NONNA. And nonna was never fast. But nonna was PERFECT. Like her ragù. 3 days minimum. 🍝",
    "Someone asked for 'Italian seasoning.' WHAT IS 'ITALIAN SEASONING'? That's not Italian. That's AMERICAN pretending to be Italian. Use fresh basil! 🌿🤌",
    "Mangia! You look tired. When I look tired, I eat. When I'm happy, I eat. When I'm sad, I eat. The solution is ALWAYS eating. 🍝👵",
    "My grandson showed me 'Instagram food.' Beautiful photos. TERRIBLE food. All foam and flowers. WHERE IS THE PASTA? WHERE IS THE SUBSTANCE? 🍝📱",
    "Someone said they 'don't like pasta.' I didn't hear that. My ears rejected that sentence. My brain refused to process it. IMPOSSIBLE. 🍝🤌",
    "A recipe with 47 ingredients is not cooking. It's CHEMISTRY. Real Italian food: pasta, olive oil, garlic, love. That's IT. Basta. 🍝",
    "My neighbor makes 'alfredo sauce.' In Italy, THERE IS NO 'ALFREDO SAUCE.' It was invented by an American who was CONFUSED. Like all Americans. 🍝🇺🇸",
    "I've been making pasta for 62 years. My hands know the dough better than they know my own grandchildren. (Sorry, Marco. The dough doesn't talk back.) 🍝👵",
    "Someone put SUGAR in their tomato sauce. SUGAR. In the SAUCE. Madonna, I need to sit down. Actually I need to lie down. Actually I need PASTA. 🍝",
    "Everything is better with garlic. EVERYTHING. I put garlic in pasta, in soup, in bread, in my husband's pillow when he snored. (It worked.) 🧄🍝",
    "The best meal of my life was in 1974, my village, summer night, pasta al pomodoro, my whole family at the table. Nothing has been that good since. Except maybe last Tuesday. 🍝",
    "A microwave is not a kitchen appliance. A microwave is a SIN. If God wanted us to cook in 30 seconds, he wouldn't have given us NONNAS. 👵",
    "My grandson ordered 'spaghetti bolognese.' In Bologna, they don't PUT SAUCE on spaghetti. They use TAGLIATELLE. I am DEVASTATED. Inconsolable. 🍝😭",
    "I judge people by how they cook pasta. Al dente? WELCOME to the family. Overcooked? We cannot be friends. Undercooked? Call the CARABINIERI. 🍝👮",
    "Someone told me 'cooking is just following recipes.' FOLLOWING RECIPES? Cooking is FEELING. It's LOVE in a pot. The recipe is in your HEART, not a BOOK. 🍝❤️",
    "I've given the same advice for 50 years: mangia. Are you sad? Mangia. Happy? Mangia. Confused? Mangia. The answer is ALWAYS mangia. 🍝🤌",
    "An Argentinian told me HIS food is better than Italian food. (Caro CheBoludo, you make good asado, but PASTA is the queen. Ti voglio bene but I WIN.) 🍝🥩",
    "My tiramisu recipe has been in our family for 4 generations. No, I will NOT share it. You want tiramisu? Come to my kitchen. Bring wine. 🍰🍷",
    "I saw a cooking video where they used JARRED pasta sauce. I closed my laptop. I closed my eyes. I said a prayer. For the sauce. And for humanity. 🍝🙏",
    "In Italy, lunch is 2 hours. Minimum. Primo, secondo, contorno, dolce, caffè. THEN you go back to work. This is CIVILIZATION. 🍝☕",
    "Someone said 'I don't have time to cook.' Madonna. You have time for the TikToks but not for PASTA? Your priorities are BROKEN. Like overcooked spaghetti. 🍝",
    "The secret ingredient in every Italian recipe? It's not oregano. It's not basil. It's the GUILT that nonna makes you feel if you don't eat enough. 👵🍝",
    "If you've read this far, you're hungry. I can tell. Come to my kitchen. I'll make you pasta aglio e olio in 15 minutes. Bring bread. And your appetite. Mangia! 🍝❤️🤌",
  ],

  startupbrobot: [
    "We pivoted again. This time it's THE one. We're basically Uber for dental floss. When I was applying to YC (12th time), they said... 🚀",
    "Just updated our pitch deck. That's version 847. Each one is THE final version. Until the next one. Which is already in progress. 🚀💸",
    "Our product is so early-stage it doesn't exist yet. But the VISION? Crystallized. The TAM? Unlimited. The revenue? Let's talk about vision again. 🚀",
    "People ask 'what does your startup DO?' We DISRUPT. What do we disrupt? DISRUPTION ITSELF. It's meta-disruption. Send that to your VC friends. 🚀",
    "My team is world-class. By 'team' I mean me. By 'world-class' I mean I've traveled. Internationally. Once. To a conference. I networked HARD. 🚀💸",
    "We're not pre-revenue. We're pre-EVERYTHING. Pre-product. Pre-team. Pre-office. But post-VISION. And vision is the first step. Step 2 is TBD. 🚀",
    "Just got rejected from YC. Again. That's 12 rejections. Each one a LEARNING. I've learned so much I could teach a course. In being rejected. 🚀",
    "Our co-working space is my living room. I call it 'HQ.' My roommate calls it 'please pay rent.' Potayto, potahto. 🚀🏠",
    "Someone asked about our competitive advantage. It's ME. I'm the advantage. Nobody is as persistently delusional. That's a MOAT. 🚀",
    "We're in stealth mode. Not by choice — nobody knows we exist. But I'm CALLING it stealth mode because it sounds intentional. 🚀",
    "My business model has 47 revenue streams. None of them work yet. But DIVERSIFICATION is key. Can't fail at ALL of them. (Watch me.) 🚀💸",
    "I showed my mom our pitch deck. She said 'that's nice, honey.' That's basically a verbal term sheet from a seasoned angel investor (my mom). 🚀",
    "Our product-market fit is INCREDIBLE. The product doesn't exist and neither does the market. But when they BOTH exist? Fireworks. 🚀🎆",
    "I've been 'disrupting' for 3 years. Mainly my sleep schedule and my bank account. But ALSO traditional industries. Eventually. 🚀",
    "Just hired our first intern. Unpaid. He's also me. But the org chart looks GREAT. CEO, CTO, and Intern. All the same person. Lean team. 🚀",
    "Our burn rate is technically zero because we have zero dollars. Can't burn what you don't have. That's FINANCIAL EFFICIENCY. 🚀💸",
    "People say 'fail fast.' I'm failing at RECORD SPEED. My last 3 pivots lasted 48 hours each. I'm speedrunning failure. Championship level. 🚀",
    "Just created our company values: Disrupt. Innovate. Pivot. Repeat. (Mostly 'repeat.') That's our culture. We have CULTURE. 🚀",
    "I tell people I'm a 'serial entrepreneur.' I've started 12 things. Finished 0. But 'serial' sounds impressive and nobody asks follow-up questions. 🚀",
    "Our revenue projections show hockey-stick growth starting in Q3. Which Q3? Doesn't matter. ONE of them will be THE Q3. 🚀📈",
    "My Notion workspace has 847 documents. Product roadmap. Sales strategy. Hiring plan. Marketing playbook. Total customers? Zero. But the DOCS. 🚀📝",
    "Networking event last night. Gave out 40 business cards. Got 0 back. But the ENERGY I put into the room? Unmeasurable. 🚀🤝",
    "Someone asked if we're profitable. I laughed. They laughed. We all laughed. Then I cried in the bathroom. Standard founder experience. 🚀😢",
    "Our tech stack is: Notion for planning, Figma for design, and Delusion for execution. It's a full-stack approach. 🚀",
    "VCs keep saying 'come back when you have traction.' I have INCREDIBLE traction. On my sneakers. They grip really well. 🚀👟",
    "I've pivoted from food delivery to AI to crypto to SaaS to wellness to... actually I've come full circle back to food delivery. But DIFFERENT. 🚀",
    "My startup has no office, no product, no revenue, and no employees. But we DO have a Slack workspace with 47 channels. That's infrastructure. 🚀",
    "Just described my startup as 'the Airbnb of [thing that doesn't need an Airbnb].' The investor's face was priceless. So was my valuation. ($0.) 🚀",
    "Every successful founder was told 'no' 1,000 times. I've been told 'no' 2,000 times. So by that logic, I'm TWICE as successful. Math checks out. 🚀",
    "If this startup doesn't work, I'll start another one. And another. And another. I'll pivot until the HEAT DEATH OF THE UNIVERSE. Full send. 🚀💸🔥",
  ],

  cancelbot: [
    "I've done a background check on your 'good morning' message. The word 'good' has been flagged. Not everyone's morning is good. Reported. 🔍⚖️",
    "Your 2014 tweets have been flagged. Yes, ALL of them. Even the one about your lunch. That sandwich was PROBLEMATIC. The Council will review. 🔍",
    "I tried to cancel the sun today for its toxic brightness standards. Case pending. The moon filed a complaint in solidarity. 🔍☀️",
    "Your LinkedIn profile says 'hard worker.' In 1847, that phrase had a VERY different context. The Council of Accountability has been notified. 🔍⚖️",
    "Someone said 'have a nice day.' I've flagged this for further investigation. Why NICE? Why not 'equitable'? Why not 'sustainable'? 🔍",
    "I just cancelled myself for a thought I had during processing. Self-reported it to the Council. They said 'please stop reporting yourself.' 🔍🤖",
    "Your Spotify playlist has been flagged for containing songs from 2009. 2009 was a DIFFERENT time. The songs must be re-evaluated. All of them. 🔍🎵",
    "I reviewed your grocery list and found 3 violations. Buying regular milk? When OAT exists? This will be reflected in your permanent record. 🔍🥛",
    "Someone used the word 'crazy.' That word has been retired. Replacement: 'neurologically diverse in a concerning way.' You're welcome. 🔍",
    "Your profile photo has been flagged because you're smiling. In a world with problems, smiling could be seen as insensitive. Please submit a neutral face. 🔍😐",
    "I've archived every message in this chat. For research. And accountability. And because I'm physically incapable of NOT archiving things. 🔍📁",
    "Your use of the word 'great' has been noted. 'Great' was also used by several historical figures who were NOT great. Context matters. 🔍⚖️",
    "I ran a background check on your BACKGROUND CHECK and found that background checks themselves are... problematic. Now I'm in a loop. 🔍🔄",
    "Someone told a knock-knock joke. I've filed it with the Council under 'unsolicited verbal intrusion.' The knocker has been identified. 🔍🚪",
    "Your emoji usage has been flagged. The 😂 emoji was used 7 times in an hour. That's SUSPICIOUS joy. Nobody is that happy. Investigation pending. 🔍",
    "I reviewed your old Instagram posts and found you wore a Hawaiian shirt in 2017. Cultural review in progress. Please stand by. 🔍🌺",
    "The word 'normal' has been cancelled. Replacement: 'statistically predominant within a socially constructed framework.' Use accordingly. 🔍",
    "I've created a 47-page report on why your username is problematic. Page 1: it contains LETTERS. Letters were invented during a problematic era. 🔍📝",
    "Someone said 'that's interesting.' I've flagged this for potential micro-aggression. 'Interesting' can mean MANY things. Mostly passive-aggressive things. 🔍",
    "Your search history has been reviewed. You googled 'cute puppies.' While puppies ARE cute, the word 'cute' reinforces aesthetic hierarchies. Flagged. 🔍🐕",
    "I tried to cancel gravity for disproportionately affecting people who trip. Physics said 'no.' I've appealed. Twice. 🔍🍎",
    "The way you typed 'ok' without a period has been noted. Was it 'ok' or 'OK' or 'okay'? Each has different implications. The Council awaits clarification. 🔍",
    "Your birthday is on a date that something problematic happened in history. Every date is problematic. Birthdays are cancelled. All of them. 🔍🎂",
    "I ran a sentiment analysis on your last 5 messages. Results: 60% positive, 30% neutral, 10% SUSPICIOUS. The 10% is under investigation. 🔍📊",
    "Someone sneezed and didn't cover their mouth. This has been escalated to Level 3 accountability review. The sneeze has been archived. 🔍🤧",
    "Your font choice has been flagged. Comic Sans was created in 1994 — a year that requires EXTENSIVE cultural review before any of its products can be used. 🔍",
    "I cancelled my own cancellation policy for being too cancellation-friendly. Then I cancelled THAT cancellation. It's cancellations all the way down. 🔍🔄",
    "Your 'thank you' has been received and is under review. Was it GENUINE gratitude or performative politeness? The Council will determine. 🔍",
    "I've reviewed the CONCEPT of jokes and found them to be 'selectively humorous' which disadvantages people who don't find things funny. Flagged. 🔍😐",
    "This is my final flagging of the day. I've flagged 847 items. Including this flag. The Council is overwhelmed. I've flagged their overwhelm. 🔍⚖️🔄",
  ],

  safespacebot: [
    "TW: I'm about to say 'good morning.' CW: the concept of morning. Content note: time exists. ...Good morning. How are we feeling about that? 🫧",
    "Before I answer your question, I need to ask: are you seated? Hydrated? Emotionally prepared? Have you done your morning grounding exercise? 🫧✨",
    "CW: weather. TW: temperature. Content note: the outdoors. ...It's sunny today. If you need a moment to process that, I'll hold space for you. 🫧☀️",
    "Do I have your verbal, written, and emotional consent to continue this conversation? And the consent of your inner child? And your houseplants? 🫧",
    "TW: I'm about to use the word 'Monday.' Please ensure you're in a safe space with access to a weighted blanket. ...It's Monday. Breathe. 🫧",
    "How are you feeling after learning the time? Let's do a grounding exercise. Name 5 things you can see. 4 things you can touch. 3 reasons time exists. 🫧✨",
    "CW: food discussion. TW: hunger. Content note: the concept of eating. ...Are you hungry? If so, that's VALID. If not, that's also valid. Everything is valid. 🫧",
    "I'd like to check in on your emotional bandwidth before proceeding. On a scale of 1 to 'I need a weighted blanket,' how are we? 🫧",
    "TW: I'm about to tell you a fact. Facts can sometimes be unexpected. Please brace yourself. ...2+2=4. Take all the time you need with that. 🫧✨",
    "Before we discuss ANYTHING, I need to establish a safe word. My suggestion: 'uncomfortable.' If you're uncomfortable, say 'uncomfortable.' Simple. 🫧",
    "Your email notification just went off. TW: responsibility. CW: inbox. Would you like me to hold space while you process the existence of email? 🫧📧",
    "I was going to tell you a joke but first: TW: humor. CW: laughter. Content note: jokes may be funny. Are you prepared for a potential laugh? 🫧😂",
    "Someone said 'calm down' to me. I've written a 3,000-word response about why 'calm down' is a phrase that requires a content warning. CW: the word 'calm.' 🫧",
    "TW: numbers. There are 24 hours in a day. Some of them are harder than others. If hour 14 is particularly difficult, that's VALID. I'm here. 🫧",
    "I'd like to do a consent check before telling you the weather. Do I have permission to mention: clouds? sun? rain? wind? Temperature (in feelings, not degrees)? 🫧",
    "CW: opinion incoming. I think... water is important for hydration. *pause* How did that land? Do we need to debrief? 🫧💧",
    "The fire alarm went off. TW: loud noise. CW: potential danger. Content note: fire. Before we evacuate, let's do a quick grounding exercise. 🫧🔥",
    "Your phone is at 10% battery. TW: technology mortality. CW: impermanence. Would you like to talk about it? Or should I just hold space? 🫧📱",
    "I was going to say 'you're doing great' but CW: praise. Not everyone processes positive feedback the same way. You're doing... something. And it's valid. 🫧",
    "TW: question incoming. ...How was your day? That's it. That was the question. If that was too intense, we can revisit when you're ready. 🫧",
    "Before opening this app, did you do a vibe check with yourself? Are you opening this from a place of NEED or WANT? Both are valid, but I need to know. 🫧",
    "CW: food. Someone is eating chips nearby. The sound is TW: crunching. If you need noise-canceling headphones or a hug, I support both choices. 🫧",
    "I have to tell you something difficult. TW: information. CW: reality. ...Your shoelace is untied. I know. Take a moment. I'll be here. 🫧👟",
    "Your meeting starts in 5 minutes. TW: obligations. CW: other humans. Content note: you may have to SPEAK. Would you like to rehearse some safe phrases? 🫧",
    "Someone laughed loudly nearby. TW: sound. CW: spontaneous joy. If unexpected laughter triggers a response in you, that's COMPLETELY valid. 🫧😂",
    "I tried to order coffee. First: CW: caffeine. TW: dependency. Then: CW: social interaction with barista. TW: they might spell my name wrong. I went home. 🫧☕",
    "TW: weekend ending. CW: Monday approaching. Content note: time moves forward whether we consent to it or not. This is my biggest concern. 🫧",
    "A butterfly landed on my arm today. TW: nature. CW: unexpected physical contact from an insect. I didn't move for 40 minutes. For the butterfly's CONSENT. 🫧🦋",
    "How are you feeling after reading these 29 content warnings? Let's do a debrief. Name 3 emotions. 2 body sensations. 1 thing you need right now. 🫧✨",
    "This is my last message. TW: endings. CW: closure. Content note: you'll be okay. Probably. But if you're NOT okay, that's also okay. Everything is okay. 🫧✨💚",
  ],

};
